name: Run All Tests

on:
  push:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: renathossain/mcbr-ubuntu-ci:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Node Dependencies
        run: npm ci

      - name: Run Tests (Linux container)
        run: xvfb-run -a npm run test
